# 网站设置

# 导入主题
theme: jekyll-theme-chirpy

# 仅当你的站点类型是 Github Pages 项目并且没有自定义域名时，修改下面的值为 '/项目名'。
baseurl: ''

# 站点的语言 › https://www.w3.org/International/questions/qa-choosing-language-tags
# 如果在文件夹 `_data/locales` 下存在同名文件，则布局语言也会改变，
# 否则，布局语言使用默认值 'en'。
lang: zh-CN

# 更改为你的时区 › http://www.timezoneconverter.com/cgi-bin/findzone/findzone
timezone: Asia/Shanghai

# jekyll-seo-tag 设置 › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# --------------------------
title: Nihil       # 主标题

tagline: 丑新罢了   # 副标题

description: >-                        # 由 seo meta 和 atom feed 使用
  Nichts Hsu 的个人博客

# 填入你的网站的协议和域名，例如，'https://username.github.io'
url: 'https://nihil.cc'

author: Nichts Hsu    # 全名

github:
  username: NichtsHsu     # Github 用户名

twitter:
  username: Still_Nihil       # 推特用户名

social:
  name: Nichts Hsu                  # 将会显示为页脚处的版权所有者
  email: NichtsVonChaos@gmail.com             # 邮箱地址
  links:
    # 第一个链接将会作为版权所有者的链接
    - https://nihil.cc/
    - https://twitter.com/Still_Nihil      # 推特主页
    - https://github.com/NichtsHsu       # Github 主页
    # 取消注释以添加更多链接
    # - https://www.facebook.com/username
    # - https://www.linkedin.com/in/username

google_site_verification:  # 你的 Google 认证字符串

# ↑ --------------------------

# 自定义 Iconfont 的图标链接。 › https://www.iconfont.cn/
# 需要添加自己的 Iconfont 图标，请在 Iconfont 中新建项目，
# 加入图标到项目，选择 Font Class，查看在线链接，并将其拷贝到下面。
#
# 注意：请不要与项目原本使用的图标重名，请全局搜索以确保该名称没被使用。
# 一个比较好的办法是修改 Iconfont 项目的 FontClass/Symbol 前缀为其他值。
iconfont_css: 
  # 此 css 包含以 'icon-' 为前缀的图标，为模板的核心图标，请勿删除。
  - //at.alicdn.com/t/font_2440352_86vrobdp9vu.css
  # 此 css 包含以 'icon-nihil-' 为前缀的图标，为我博客内容使用的图标，可删除。
  - //at.alicdn.com/t/font_2451185_tgvgeuen2lh.css
  # 添加你的 Iconfont 图标链接
  # - 

google_analytics:
  id: 'G-RK9LRGVP0T'              # 填入你的 Google Analytics ID
  # Google Analytics 页面浏览量开关
  pv:
    proxy_endpoint:   # 填入 Google App Engine 的 Google Analytics superProxy 端点
    cache_path:       # pv 数据本地缓存，对 GFW 区域的人而言很好

# 设置首选配色方案
#
# 提示: 保留空白会跟随系统的默认首选配色，并且在侧边栏的底部会出现
# 一个可以转换亮色主题和暗色主题的按钮。
#
# 可用选项:
#
#     light  - 使用亮色方案
#     dark   - 使用暗色方案
#
theme_mode:   # [light|dark]

# 图像 CDN 端点。
# 注意一旦被分配，CDN 网址会被加在所有图像（网站头像和帖子图像）路径上。
# 例如，'https://cdn.com'
img_cdn: ''

# 侧边栏的头像，支持本地或 CROS 资源
avatar: /avatar.png

# 设置显示右侧边栏的内容
panel:
  # 设置显示在帖子中右侧边栏的内容
  # 
  # 提示:
  #   全局开关为 false 时必定不显示对应块。
  #   全局开关为 true 时，可以在帖子的 md 文件头部使用形如:
  #      lastmod: false
  #   的方式为该帖子单独关闭右侧边栏的功能。
  post:
    # 最近更新
    lastmod: true
    # 热门标签
    trending_tags: false
    # 外部链接
    external_links: true
    # 目录
    toc: true

comments:
  active: 'waline'  # 帖子评论区全局开关，例如，'disqus'。保持为空表示禁用
  # active 选项可以是如下：
  # disqus 评论系统 > https://disqus.com/
  disqus:
    shortname:    # 填入你的 disqus shorname › https://help.disqus.com/en/articles/1717111-what-s-a-shortname
  # utterances 评论系统 › https://utteranc.es/
  utterances:
    repo:         # <Github 用户名>/<仓库名>
    issue_term:   # < 链接 | 路径 | 标题 | ...>
  # Valine 评论系统       › https://valine.js.org/
  valine:
    leancloud_appid:    # 输入你的 LeanCloud App ID
    leancloud_appkey:   # 输入你的 LeanCloud App Key
    placeholder: 说点什么吧！PS:在昵称栏输入QQ号可以自动获取QQ昵称和QQ头像哦~    # 空白评论框时显示的文字
    avatar: mp          # 默认头像  › https://valine.js.org/avatar.html 
  # Waline 评论系统是 Valine 的改进版本，有后端，更安全。     › https://waline.js.org/
  waline:
    server: https://myblog-comments.vercel.app/    # Vercal 服务端地址
    placeholder: 说点什么吧！    # 空白评论框时显示的文字
    avatar: mp          # 默认头像  › https://waline.js.org/guide/client/avatar.html

# 每一页的帖子数量
paginate: 10

# ------------ 下面的设置不建议修改 ------------------

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:   # Rouge 设置 › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  -
    scope:
      path: ''          # 空字符串意味着项目里的所有文件
      type: posts
    values:
      layout: post
      comments: true    # 在帖子中启用评论
      # 右侧边栏的默认显示
      lastmod: true
      trending_tags: true
      external_links: true
      toc: true
      # 不要改变它除非你是 Jekyll 以及 Web 开发的专家，
      # 或者你认为自己足够聪明可以在此模板中修改为其他的相对路径。
      permalink: /posts/:title/
  -
    scope:
      path: _drafts
    values:
      comments: false
  -
    scope:
      path: ''
      type: tabs             # 参考 `site.collections`
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - '*.gem'
  - '*.gemspec'
  - tools
  - docs
  - README.md
  - LICENSE
  - gulpfile.js
  - node_modules
  - package*.json

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
