# Site settings 配置站点
title: 'Mr Li'
description: '个人的一个技术博客站点，主要用于记录个人在学习过程中遇到的技术问题及解决方法、技术实验，以及一些比较有趣的事情。'
keyword: 'zhonger，zhonger的博客，nodejs，kvm, 机器学习'
url: '' # your host

# when build blog on server, if you don't need baseurl, you should leave this value blank.
# 在服务器上建站时，如果你不需要子域名，请将这一格留空
# if you're using GitHub Pages, set baseurl to your blog's .
# 如果你在使用 GitHub Pages, 请将 baseurl 设置为你的网址的子域名
# for example, if your site is "kaeyleo.github.io", then this url should leave blank.
# 例如，当你的域名是 "kaeyleo.github.io"  时，这个 url 需要留空
# but if your created a repo named "myblog", and the site is "kaeyleo.github.io/myblog", change baseurl to '/myblog'
# 但是，如果你创建了一个叫 "myblog" 的网站，此时网址会变成 "kaeyleo.github.io/myblog" ，这时再将 baseurl 设置为 '/myblog'
baseurl: ''

# International
language: zh-cn

# Navigation links
nav:
  home: '/'
  blog: '/blog/index.html'
  archives: '/archives.html'
  tags: '/tags.html'
  RSS: '/feed.xml'
  logs: '/logs.html'

# Footer
footer:
  since: 2015

# Author 配置博主信息
author: 'zhonger'
nickname: 'zhonger'
bio: '全栈开发者，热爱前端、运维和架构设计'
avatar: '/assets/img/profile.webp'

# Search
search: true

# Night mode
nightMode: false

# Comments 评论功能
comments:
  disqus: false
  disqus_url: 'https://liaokeyu.disqus.com/embed.js'

# MathJax 公式支持 by Ray-Eldath
mathjax: true

# Share
social-share: true
social-share-items: ['wechat', 'weibo', 'douban', 'twitter']

# theme color 主题皮肤
theme-color: 'default'  # pink or default

# Post header background patterns (when the post no cover): circuitBoard, overlappingCircles, food, glamorous, ticTacToe, seaOfClouds
postPatterns: 'circuitBoard'

# SNS settings 配置社交网站
# url: email, weibo, zhihu, twitter, instagram, juejin, github, douban, facebook, dribble, uicn, jianshu, medium, linkedin
sns:
  google-scholar: 'https://scholar.google.com/citations?user=AUupIooAAAAJ'
  researchgate: 'https://www.researchgate.net/profile/Shengzhou-Li'
  ORCID: 'https://orcid.org/0000-0001-6973-3825'
  github: 'https://github.com/zhonger'
  linkedin: 'https://www.linkedin.com/in/shengzhouli/'
  segmentfault: 'https://segmentfault.com/u/wuwozhonger'

# Links 友情链接
links:
  'Mr Li': 'https://lisz.me'

# Beian 备案号
beian: '沪ICP备xxxxxxxx号'

# CC License
cclicense: true

# CNZZ Analytics
# cnzz: 1234567891
cnzz: 

# Google Analytics
# google_analytics: UA-XXXXXXXXX-X
google_analytics: 

# Tags 设置标签
recommend-tags: true # whether or not display recommend-tags on the sidebar
recommend-condition-size: 12 # a tag will be recommended if the size of it is more than this value

# Build settings
paginate: 10
paginate_path: 'blog/page:num'
exclude: ['node_modules', 'dev', 'package.json', 'gulpfile.js', '.gitignore', 'README.md', '*.gemspec', '*.gem']

# Markdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

# RSS
RSS: true

# Permalink
# See: https://github.com/kaeyleo/jekyll-theme-H2O/issues/35
permalink: /:categories/:title.html

# TOC
toc: true

# Plugins
plugins: [jekyll-paginate, jekyll-feed, jekyll-sitemap]
